from math import copysign
from typing import cast, List

import frappe
from erpnext.stock.doctype.item.item import Item
from frappe.tests.utils import FrappeTestCase, change_settings
from frappe.utils import rounded

from ksa_compliance.output_models.models import TaxCategoryByItems, TaxCategory, ZatcaTaxCategory, TaxSubtotal
from ksa_compliance.output_models.tax import create_tax_total


class TestTax(FrappeTestCase):
    @change_settings('System Settings', {'rounding_method': 'Commercial Rounding'})
    def test_negative_zero_detection_for_total_discount(self):
        # This test data is generated by the example given here:
        # https://github.com/lavaloon-eg/ksa_compliance/issues/362#issuecomment-4845192286
        # The original item I started with (Demo Item) was priced at 500, and I adjusted the rate down to 4.0 and
        # 13.0 over two lines on a system running with 4-digit currency precision
        taxes = TaxCategoryByItems(
            tax_category=TaxCategory(
                zatca_tax_category_id=ZatcaTaxCategory(tax_category_code='S', reason_code=None, arabic_reason=None),
                percent=15,
                tax_scheme_id='VAT',
            ),
            items=[
                cast(
                    Item,
                    frappe.get_doc(
                        {
                            'doctype': 'Item',
                            'idx': 1,
                            'qty': 1.0,
                            'uom': 'Nos',
                            'item_code': 'Demo item',
                            'item_name': 'Demo item',
                            'net_amount': 3.4783,
                            'rate': 4.0,
                            'discount_percentage': 99.2,
                            'tax_percent': 15.0,
                            'amount': 3.48,
                            'rounding_amount': 4.0017,
                            'base_amount': 499.48,
                            'discount_amount': 496.0,
                            'tax_amount': 0.5217,
                            'item_tax_template': None,
                            'allowance_charge_reason': 'Discount',
                            'allowance_charge_reason_code': 95,
                            'tax_category': {
                                'zatca_tax_category_id': {
                                    'tax_category_code': 'S',
                                    'reason_code': None,
                                    'arabic_reason': None,
                                },
                                'percent': 15.0,
                                'tax_scheme_id': 'VAT',
                            },
                        }
                    ),
                ),
                cast(
                    Item,
                    frappe.get_doc(
                        {
                            'doctype': 'Item',
                            'idx': 2,
                            'qty': 1.0,
                            'uom': 'Nos',
                            'item_code': 'Demo item',
                            'item_name': 'Demo item',
                            'net_amount': 11.3043,
                            'rate': 13.0,
                            'discount_percentage': 97.4,
                            'tax_percent': 15.0,
                            'amount': 11.3,
                            'rounding_amount': 12.995600000000001,
                            'base_amount': 498.3,
                            'discount_amount': 487.0,
                            'tax_amount': 1.6956,
                            'item_tax_template': None,
                            'allowance_charge_reason': 'Discount',
                            'allowance_charge_reason_code': 95,
                            'tax_category': {
                                'zatca_tax_category_id': {
                                    'tax_category_code': 'S',
                                    'reason_code': None,
                                    'arabic_reason': None,
                                },
                                'percent': 15.0,
                                'tax_scheme_id': 'VAT',
                            },
                        }
                    ),
                ),
            ],
        )
        totals = create_tax_total({'S15': taxes})
        subtotals = cast(List[TaxSubtotal], totals['tax_subtotal'])
        discount = rounded(subtotals[0].total_discount, 2)
        self.assertEqual(0.0, discount, 'Expected total_discount to be 0.0')
        self.assertEqual(copysign(1.0, discount), 1.0, 'Expected discount sign to be 1.0 (for non-negative 0.0)')
